### ISSUE TITLE
TypeError: bcast() takes at least 1 positional argument (0 given)

### ISSUE THREAD

**Issue by omerarshad** [pengli09/str2vec#1]
training stucks at 

load word vectors...
preparing data...

**Comment by omerarshad** [comment]
load word vectors...
Traceback (most recent call last):
  File "/home/omer/str2vec-master/src/nn/lbfgstrainer.py", line 380, in <module>
    instances, word_vectors, total_internal_node = prepare_data()
  File "/home/omer/str2vec-master/src/nn/lbfgstrainer.py", line 209, in prepare_data
    word_vectors = comm.bcast(root=0)
  File "MPI/Comm.pyx", line 1273, in mpi4py.MPI.Comm.bcast (src/mpi4py.MPI.c:108777)
TypeError: bcast() takes at least 1 positional argument (0 given)
preparing data...

**Comment by pengli09** [comment]
Sorry for late response. The problem seems to be cased by incompatible version of mpi4py or open-mpi. Please try mpi4py 1.3.1 and open-mpi 1.8.1.

**Comment by omerarshad** [comment]
Sure, i'll try this. Thanks a lot for your response. DO you know of any
other implementation of RAE in java? Your.r implementation is best i found
on github.

Ome

**Comment by pengli09** [comment]
Sorry but I don't know whether there is any Java implementation.

**Comment by omerarshad** [comment]
Hi!

is there any easy way to install mpi4py 1.3.1? i am unable to find it.

Thanks, Omer

**Comment by pengli09** [comment]
here is mpi4py 1.3.1 https://pypi.python.org/pypi/mpi4py/1.3.1

**Comment by pengli09** [comment]
By the way, have a look at [virtualenv](https://virtualenv.readthedocs.org/en/latest/), it may be helpful for separating your development environment from the system wide one.

**Comment by omerarshad** [comment]
thanks for your help, i have a sentence that always have 3 words and i want
to give three words together to RAE. For that i have made few changes in
you code and using same objective function it converges as well. But the
weights it learn are very poor. e.g.  *\* for each sentence now i have only
one internal node **
          0.000001,
          -0.00000002
          0.00000001
         -0.00000000
         -0.00000001
          0.00000001
         -0.00000001
         -0.00000001

Can you help me in it? I'll be really thankful to you.

**Comment by pengli09** [comment]
Please make sure the gradients are computed correctly. Usually a technique
name as"gradient checking" is used. Please refer to
http://deeplearning.stanford.edu/wiki/index.php/Gradient_checking_and_advanced_optimization
for further information and see src/gradutil.py for example.

**Comment by omerarshad** [comment]
I am calculating the gradient correctly, i found that if i fix the size of
sentence to two words, it learns same weights as i sent u before. Does it
mean that we can fix the size of sentence to two?

**Comment by omerarshad** [comment]
Hi !

I want to know which dataset you used to train RAE?

Thanks, Omer

**Comment by pengli09** [comment]
Please refer to the paper Recursive Autoencoders for ITG-based Translation for more information. Usually RAEs are used in semi-supervised way, i.e. the paper mentioned above. I don't include the supervised part in this code. However, you can add the supervised part easily in __backward() when processing LeafNode.

**Comment by omerarshad** [comment]
sorry i am bit confused, I am just using RAE to get a sentence vector
representation. DO i need a semi supervised RAE for that?

**Comment by pengli09** [comment]
No but not guaranteed to produce satisfied results. As far as I know, RAEs
are rarely used in fully unsupervised case.

**Comment by omerarshad** [comment]
alright, so how to test accuracy of our learned sentence vectors? we are
performing Semantic similarity, that means more accuracy we obtain in
semantic similarity, means good vectors we have obtained.

**Comment by pengli09** [comment]
Maybe it's a reasonable way. There isn't a golden measure for such purpose,
it depends on you.

**Comment by omerarshad** [comment]
yes actually there is no defined way to measure how good vectors we have
obtained. anyways thanks for your help

**Comment by omerarshad** [comment]
Hello ! I appreciate your great help, Can i get your code for supervised
learning? where gradients are updated and error is added to training
objective function? Actually i am running out of time for my thesis so it
will really help me.

Best regards,
Omer

**Comment by pengli09** [comment]
I'm sorry but the code is a shared property between my school and a
company, so I can't release it.

**Comment by omerarshad** [comment]
ok. thanks :)

**Comment by omerarshad** [comment]
one more thing, i noticed that you didn't used alpha (learning rate), am i
right?

**Comment by pengli09** [comment]
yes, LBFGS does not have this parameter

**Comment by omerarshad** [comment]
Hello!
1) you said before "you can add the supervised part easily in __backward()
when processing LeafNode." , i have a question that do we have to execute
supervised code when every single leaf node is processed? or when whole
tree is processed? As i want to compare semantic similarity between two
sentence vectors after computing their vectors.

Guide me where i am wrong, Its great that researchers like you help us as
we don't have such supervisors here.

Thanks.
Omer

**Comment by pengli09** [comment]
Maybe the paper "Bilingually-constrained Phrase Embeddings for Machine
Translation" can help you to design you model.

Forget about  "you can add the supervised part easily in __backward() when
processing LeafNode", it holds only the supervised signal is provided at
LeafNode. In other words, how to compute the gradient depends on your
model. If you only have supervised signal for a whole sentence, then you
properly need to compute the corresponding gradients outside backward() and
pass propagate errors (\delta) to backward() using the
parameter delta_parent.

**Comment by pengli09** [comment]
Maybe the paper "Bilingually-constrained Phrase Embeddings for Machine Translation" can help you to design you model. Forget about  "you can add the supervised part easily in __backward() when processing LeafNode", it holds only the supervised signal is provided at LeafNode. In other words, how to compute the gradient depends on your model. If you only have supervised signal for a whole sentence, then you properly need to compute the corresponding gradients outside backward() and pass propagate errors (\delta) to backward() using the parameter delta_parent.

**Comment by omerarshad** [comment]
Hi! Are you using random weights or gaussian distribution in your
experiments?

**Comment by pengli09** [comment]
see src/nn/util.py init_W()

**Comment by omerarshad** [comment]
Hello ! i am using your implementation of RAE, i want to know that how can
i change your scipy minimization to manual eopcs?

**Comment by omerarshad** [comment]
Hi!
Are you calculating 2nd order derivatives in your implementation of RAE?

Omer.
